####################################################################################################
# Creating container PHP
####################################################################################################
php_story:
    build: ./service
    container_name: php_story
    volumes:
        - ./service/:/var/www/html
    ports:
        - "9116:80"
