####################################################################################################
# Creating container PHP
####################################################################################################
php1:
    build: ./service
    container_name: php_story_1
    volumes:
        - ./service/:/var/www/html
    ports:
        - "9116:9000"

php2:
    build: ./service
    container_name: php_story_2
    volumes:
        - ./service/:/var/www/html
    ports:
        - "9117:9000"

####################################################################################################
# Creating container (Nginx)
####################################################################################################

nginx1:
    image: nginx:latest
    container_name: nginx_story_1
    ports:
        - 7098:80
    volumes:
        - ./image/nginx/nginx-01.conf:/etc/nginx/nginx.conf
    links:
        - php_story_1

nginx2:
    image: nginx:latest
    container_name: nginx_story_2
    ports:
        - 7099:80
    volumes:
        - ./image/nginx/nginx-02.conf:/etc/nginx/nginx.conf
    links:
        - php_story_2

nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy_story
    ports:
        - 9100:80
    volumes:
        - ./image/nginx/nginx.proxy.conf:/etc/nginx/nginx.conf
    links:
        - nginx_story_1
        - nginx_story_2

